# Generated by Django 6.0 on 2025-12-26 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceprovider',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='contact',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='location_string',
            field=models.CharField(blank=True, help_text='Human-readable location address', max_length=500),
        ),
        migrations.AlterField(
            model_name='serviceprovider',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
