# Generated by Django 6.0 on 2025-12-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_serviceprovider_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='is_available',
            field=models.BooleanField(default=True, help_text='Whether the provider is currently available for bookings'),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='max_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price the provider charges', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='min_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price the provider charges', max_digits=10, null=True),
        ),
    ]
