# Generated by Django 6.0 on 2025-12-29 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0003_serviceprovider_is_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceprovider',
            name='is_available',
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='available_end_time',
            field=models.TimeField(blank=True, help_text='End time of availability (e.g., 17:00)', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='available_from_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='First day of availability (e.g., Monday)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='available_start_time',
            field=models.TimeField(blank=True, help_text='Start time of availability (e.g., 09:00)', null=True),
        ),
        migrations.AddField(
            model_name='serviceprovider',
            name='available_to_day',
            field=models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Last day of availability (e.g., Friday)', max_length=10, null=True),
        ),
    ]
