# Generated by Django 6.0 on 2025-12-29 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fcm_token',
            field=models.CharField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', max_length=255, null=True),
        ),
    ]
