# Generated by Django 6.0 on 2025-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_fcm_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fcm_token',
            field=models.TextField(blank=True, help_text='Firebase Cloud Messaging device token for push notifications', null=True),
        ),
    ]
