# Generated by Django

from django.db import migrations, models


def set_existing_users_verified(apps, schema_editor):
    """Existing users before this feature are considered verified."""
    User = apps.get_model('accounts', 'User')
    User.objects.all().update(is_email_verified=True)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bankaccount_wallet_wallettransaction_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_email_verified',
            field=models.BooleanField(default=False, help_text='True after user verifies email with the code sent on signup.'),
        ),
        migrations.RunPython(set_existing_users_verified, migrations.RunPython.noop),
    ]
