# Generated by Django 6.0 on 2025-12-28 04:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0002_alter_serviceprovider_address_and_more'),
        ('reviews', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='review',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('service_category__isnull', False)), fields=('provider', 'customer', 'service_category'), name='unique_review_per_service'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.UniqueConstraint(condition=models.Q(('service_category__isnull', True)), fields=('provider', 'customer'), name='unique_review_per_provider_no_service'),
        ),
    ]
