# Generated by Django 6.0 on 2025-12-29 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Final negotiated price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='Price is locked after customer accepts final price'),
        ),
    ]
