# Generated by Django 6.0 on 2025-12-29 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_final_price_booking_price_locked'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='final_price',
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_by',
            field=models.ForeignKey(blank=True, help_text='User who proposed the current price', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='price_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='proposed_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Currently proposed price during negotiation', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_locked',
            field=models.BooleanField(default=False, help_text='Price is locked after acceptance'),
        ),
    ]
