# Generated by Django 6.0

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addresses', '0002_savedaddress_latitude_longitude'),
        ('bookings', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='saved_address',
            field=models.ForeignKey(
                blank=True,
                help_text="Service address from user's saved addresses",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='bookings',
                to='addresses.savedaddress',
            ),
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(blank=True, default='', help_text='Denormalized address text (from saved_address or legacy)'),
        ),
    ]
