# Generated by Django 6.0

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='EmailSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('smtp_host', models.CharField(blank=True, help_text='e.g. smtp.gmail.com', max_length=255)),
                ('smtp_port', models.PositiveIntegerField(default=587, help_text='Usually 587 (TLS) or 465 (SSL)')),
                ('smtp_username', models.CharField(blank=True, help_text='SMTP login username/email', max_length=255)),
                ('smtp_password', models.CharField(blank=True, help_text='SMTP password or app password', max_length=255)),
                ('from_email', models.EmailField(blank=True, help_text='From address for outgoing emails', max_length=254)),
                ('use_tls', models.BooleanField(default=True, help_text='Use TLS (recommended for port 587)')),
                ('is_active', models.BooleanField(default=False, help_text='When enabled, password reset and other emails use these settings. When disabled, console backend is used.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Email settings',
                'verbose_name_plural': 'Email settings',
            },
        ),
    ]
