# Generated by Django 6.0 on 2025-12-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking_created', 'New Booking Request'), ('booking_confirmed', 'Booking Confirmed'), ('booking_accepted', 'Booking Accepted'), ('booking_negotiation', 'Booking Negotiation'), ('booking_completed', 'Booking Completed'), ('booking_cancelled', 'Booking Cancelled'), ('service_completed', 'Service Completed'), ('payment_received', 'Payment Received'), ('new_provider', 'New Provider Available'), ('verification_approved', 'Verification Approved'), ('verification_rejected', 'Verification Rejected'), ('general', 'General')], default='general', max_length=50),
        ),
    ]
